server:
  port: 8080

spring:
  main:
    web-application-type: reactive
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/auth/**
        # - id: tenant-service
        #   uri: lb://TENANT-SERVICE
        #   predicates:
        #     - Path=/tenant/**
        # - id: appointment-service
        #   uri: lb://APPOINTMENT-SERVICE
        #   predicates:
        #     - Path=/appointment/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

security:
  jwt:
    public-key-pem: ${JWT_PUBLIC_KEY}
    internal-private-key-pem: ${INTERNAL_JWT_PRIVATE_KEY}
    internal-public-key-pem: ${INTERNAL_JWT_PUBLIC_KEY}
